SELECT
    cast(_c0 AS bigint) AS index,
    cast(_c1 AS double) AS `totalviews/channelelapsedtime`,
    cast(_c2 AS char(24)) AS channelId,
    cast(_c3 AS int) AS videoCategoryId,
    cast(_c4 AS bigint) AS channelViewCount,
    cast(_c5 AS double) AS `likes/subscriber`,
    cast(_c6 AS double) AS `views/subscribers`,
    cast(_c7 AS int) AS videoCount,
    cast(_c8 AS bigint) AS subscriberCount,
    cast(_c9 AS char(11)) AS videoId,
    cast(_c10 AS double) AS `dislikes/views`,
    cast(_c11 AS bigint) AS channelelapsedtime,
    cast(_c12 AS double) AS `comments/subscriber`,
    cast(_c13 AS double) AS `likes/views`,
    cast(_c14 AS bigint) AS channelCommentCount,
    cast(_c15 AS bigint) AS videoViewCount,
    cast(_c16 AS double) AS `likes/dislikes`,
    cast(_c17 AS double) AS `comments/views`,
    cast(_c18 AS double) AS `totvideos/videocount`,
    cast(_c19 AS bigint) AS elapsedtime,
    cast(_c20 AS bigint) AS videoLikeCount,
    cast(_c21 AS bigint) AS videoDislikeCount,
    cast(_c22 AS double) AS `dislikes/subscriber`,
    cast(_c23 AS double) AS `totviews/totsubs`,
    cast(_c24 AS double) AS `views/elapsedtime`,
    cast(_c25 AS date) AS videoPublished,
    cast(_c26 AS bigint) AS VideoCommentCount
    
FROM FROM {{ ref('youtube_bronze') }}
WHERE _c0 != 'index'