
version: 2

models:
  - name: dim_youtube__videos
    columns:
    - name: id
      tests:
        - unique
        - not_null
    - name: category_id
      tests:
        - accepted_values:
            values: [1, 2, 10, 15, 17, 18, 19, 20,
                    21, 22, 23, 24, 25, 26, 27, 28,
                    29, 30, 31, 32, 33, 34, 35, 36,
                    37, 38, 39, 40, 41, 42, 43, 44]
        - relationships:
            to: ref("youtube_categories")
            field: id
    - name: date
      tests:
        - test_date_range:
            min_date: "2010-01-01"
            config:
              store_failures: true

  - name: stg_youtube__raw
    columns:
    - name: videoId
      description: "Alternative key for this table"
      tests:
        - unique
        - not_null
      required: true
    - name: channelId
      description: "Channel reference id"
      tests:
        - not_null
    - name: index
      description: "The primary key for this table"
      tests:
        - unique
        - not_null
  - name: dim_youtube__channels
    columns:
    - name: id
      tests:
        - not_null
  - name: report_youtube__category_stats
    columns:
    - name: id
      tests:
        - not_null

macros:
  - name: youtube_raw_datatypes
    description: "Datatypes for raw video data"
  - name: test_date_before
    description: "Test whether a date comes before"

